[package]
name = "audit-ceph"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
domain = { path = "../domain" }
tokio.workspace = true
