[package]
name = "metrics-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
domain = { path = "../domain" }
tracing.workspace = true
